GCOV_PROFILE := y
EXTRA_CFLAGS += -Idrivers/video/tegra/host
obj-$(CONFIG_TEGRA_GRHOST) += host/
obj-$(CONFIG_TEGRA_DC) += dc/
obj-$(CONFIG_FB_TEGRA) += fb.o
obj-$(CONFIG_TEGRA_NVMAP) += nvmap/
obj-$(CONFIG_TEGRA_HDMI_MHL) += sii9234/




#
# EternityProject 02/04/2013
# For LG Optimus 4X HD
#

obj-$(CONFIG_MACH_RGB_CONVERTOR_SPI) += ssd2825/
obj-$(CONFIG_MACH_X3) += sii9244/
