#
# Touchscreen device drivers for EPRJ ENR#U
#
# Copyright (C) 2013 EternityProject Developers
# Angelo G. Del Regno <kholk11@gmail.com
#

obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_3k)	+= synaptics_3200.o rmi_dev.o
